### ISSUE TITLE
What's the project status?

### ISSUE THREAD

**Issue by jcbhmr** [gitattributes/gitattributes#184]
Hello @alexkaratarakis ! 👋

I notice that there's a lot of open issues on this repo. Are you still actively maintaining this project? Are you looking for someone to help out? Is this project _shoved-to-the-side_-ish? Are improvements and additions encouraged? Discouraged?

In particular I notice that there's this open PR that was open so long the original poster since deleted their account 🤯 #177

@spenserblack appears to have had a similar idea to yours to make a centralized hub for .gitattributes templates/presets https://github.com/spenserblack/.gitattributes, so it might be cool to add them as a Collaborator? I'm not sure on the etiquette of asking someone else to combine projects 😅

I can also help closing/fixing/doing issues. ❤️

**Comment by Richienb** [comment]
An outstanding issue with the project is that I haven't seen any visible change in my experience when using them. I think this is because most entries seem to configure the default settings which make them just a slight waste of time to use.
I, for one, want to see the files cleaned up to just include the tweaks that haven't been accepted to https://github.com/github-linguist/linguist/

**Comment by jcbhmr** [comment]
@Richienb I agree that a lot of the stuff like `*.txt text=auto` feels a bit redundant. I like the idea of focusing on improving the experience for users with syntax highlighting features. I also like the idea of #140.

@alexkaratarakis thoughts?

**Comment by alexkaratarakis** [comment]
The project is still being maintained and improvements are very welcome! :)

Most of the open issues seem stale at quick glance so they can be closed-and-reopened-later-if-needed, just have been leaving them open for visibility - the volume is such that it could go either way. Regarding #177 , the user was deleted a few days after the PR was opened. Other PRs have been merged since then.

> I agree that a lot of the stuff like *.txt text=auto feels a bit redundant. I like the idea of focusing on improving the experience for users with syntax highlighting features. I also like the idea of https://github.com/alexkaratarakis/gitattributes/issues/140.

I agree with these. Syntax highlighting, especially, is a huge productivity boost, in my opinion.

> I, for one, want to see the files cleaned up to just include the tweaks that haven't been accepted to https://github.com/github-linguist/linguist/

Would that require users (local, non-github etc) to have `linguist` installed?

**Comment by spenserblack** [comment]
> Would that require users (local, non-github etc) to have linguist installed?

Nope. But you *can* have linguist installed locally if you want to see the benefits locally, too ;)

Linguist is what GitHub uses to build out the colored language bar, apply the appropriate syntax highlighting, etc. It works really well out of the box, but there are a few instances where it needs help. For example, a lot of `.json` files are actually `.jsonc` (JSON with Comments).
So `tsconfig.json` will get scary red highlighting for comments unless you apply an override.

`linguist-language` is the only attribute I've frequently had to use. `linguist-detectable` might be valid sometimes. For example a Jekyll project that uses Markdown, since Markdown is not detected by default.

So the large majority will only see benefits on github.com, but a few might see benefits locally, too.

**Comment by jcbhmr** [comment]
Ok you've answered my question 👍 closing as completed
